<a href="https://colab.research.google.com/github/Danishzaman-0786/SIMPLE_ANN_FORWARD_PROPOGATION/blob/main/simple_Ann%20code%20forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#simple nural network
import torch as t
import torch.nn as nn
class Simple_nn(nn.Module):
  def __init__(self,features):
    super().__init__()
    #ask,what are you add more layer
    self.hidden_layer=int(input("Numbers of Hidden_layes"))
    if self.hidden_layer==1:
      self.neurons=int(input("Numbers of neurons"))
      if self.neurons==1:
        self.l1=nn.Linear(features,self.neurons)
        self.sig_1=nn.Sigmoid()
      else:
        self.l1=nn.Linear(features,self.neurons)
        self.Rellu=nn.ReLU()
        self.l2=nn.Linear(self.neurons,1)
        self.sig_1=nn.Sigmoid()
    elif self.hidden_layer==2:
        self.first_hidden_laye=int(input("first_hidden_laye_numbers of neurons"))
        #print(self.first_hidden_laye)
        self.neurons=self.first_hidden_laye
        #print(self.neurons)
      # if self.neurons==self.neurons:
        self.l1=nn.Linear(features,self.neurons)
        print(self.l1)
        self.Rellu=nn.ReLU()
        self.second_hidden_laye=int(input("second_hidden_laye_numbers of neurons"))
        self.neurons2=self.second_hidden_laye
        self.l2=nn.Linear(self.neurons,self.neurons2)
        self.Rellu1=nn.ReLU()
        self.l3=nn.Linear(self.neurons2,1)
        self.sig_1=nn.Sigmoid()
  def forward_pass(self,x):
    if self.hidden_layer==1 and self.neurons==1:
      z1=self.l1(x)
      return self.sig_1(z1)
    elif self.hidden_layer==1 and self.neurons>1:
      z1=self.l1(x)
      relu1=self.Rellu(z1)
      y_pred=self.sig_1(relu1)
    elif  self.hidden_layer==2:
      z1=self.l1(x)
      relu1=self.Rellu(z1)
      z2=self.l2(relu1)
      relu2=self.Rellu1(z2)
      z3=self.l3(relu2)
      return self.sig_1(z3)








     # else:
      ## self.Rellu=t.rellu()
      #self.neurons=self.second_hidden_laye













In [7]:
data=t.rand(5,4)

In [8]:
model=Simple_nn(data.shape[1])

Numbers of Hidden_layes2
first_hidden_laye_numbers of neurons2
Linear(in_features=4, out_features=2, bias=True)
second_hidden_laye_numbers of neurons2


In [9]:
model

Simple_nn(
  (l1): Linear(in_features=4, out_features=2, bias=True)
  (Rellu): ReLU()
  (l2): Linear(in_features=2, out_features=2, bias=True)
  (Rellu1): ReLU()
  (l3): Linear(in_features=2, out_features=1, bias=True)
  (sig_1): Sigmoid()
)

In [10]:
model.forward_pass(data)

tensor([[0.5442],
        [0.5461],
        [0.5459],
        [0.5645],
        [0.5589]], grad_fn=<SigmoidBackward0>)

In [16]:
!pip install torchinfo

In [17]:
from torchinfo import summary as s

In [18]:
s(model,data_size=(data.shape))

Layer (type:depth-idx)                   Param #
Simple_nn                                --
├─Linear: 1-1                            10
├─ReLU: 1-2                              --
├─Linear: 1-3                            6
├─ReLU: 1-4                              --
├─Linear: 1-5                            3
├─Sigmoid: 1-6                           --
Total params: 19
Trainable params: 19
Non-trainable params: 0

In [20]:
model.l1.weight

Parameter containing:
tensor([[ 0.2236, -0.2792,  0.2864,  0.2686],
        [ 0.1089,  0.3180, -0.1584, -0.4428]], requires_grad=True)

In [22]:
model.l1.bias

Parameter containing:
tensor([-0.2094, -0.2808], requires_grad=True)

In [ ]:
SIMPLE_ANN_FORWARD_PROPOGATION